kind: pipeline
type: kubernetes
name: drone

metadata:
  namespace: drone

steps:
  - name: publish
    pull: always
    image: gcr.io/clever-circlet-125504/drone-kaniko
    settings:
      registry: gcr.io
      repo: som-laneweb/laneweb
      cache: true
      tags:
        - latest
        - "${DRONE_COMMIT_SHA}"
      json_key:
        from_secret: docker_password
    when:
      branch:
        - master

  # Job triiger by tag event      
  - name: publish-tag
    pull: always
    image: gcr.io/clever-circlet-125504/drone-kaniko
    settings:
      registry: gcr.io
      repo: som-laneweb/laneweb
      cache: true
      tags:
        - latest
        - "${DRONE_COMMIT_SHA}"
      json_key:
        from_secret: docker_password
    when:
      event:
        - tag
  
  # Job triiger by tag event 
  - name: add-last-git-tag
    pull: always
    image: gcr.io/clever-circlet-125504/gcloud
    environment:
      GCP_KEY:
        from_secret: gcp_key_base64
    commands:
      - make add-last-git-tag
    when:
      status: success
      event: 
        - tag

  - name: downstream-build
    pull: always
    image: plugins/downstream
    settings:
      server: https://drone.med.stanford.edu
      token:
        from_secret: downstream_token
      fork: true
      repositories:
        - irt-lane/kube-laneweb
    when:
      status: success

  - name: slack
    pull: always
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: irt-dcs-cicd
      username: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
      template: |
        *<${DRONE_BUILD_LINK}|Build ${DRONE_BUILD_NUMBER}>*: *{{build.status}}* in {{since build.started}}
        *Event*: ${DRONE_BUILD_EVENT} on branch ${DRONE_COMMIT_BRANCH}
        *Author*: ${DRONE_COMMIT_AUTHOR}
        *<${DRONE_COMMIT_LINK}|Commit>*: ${DRONE_COMMIT_MESSAGE}
      when:
        status:
          - success
          - failure
