# template for .drone.sec.yml
# to generate drone secrets
# see http://readme.drone.io/usage/secrets/

environment:
  REGISTRY: ${REGISTRY}
  REGISTRY_USER: ${REGISTRY_USER}
  REGISTRY_EMAIL: ${REGISTRY_EMAIL}
  REGISTRY_KEY: >
    ${REGISTRY_KEY}
  DRONE_TOKEN: ${DRONE_TOKEN}
  SLACK_URL: ${SLACK_URL}
  CHANNEL: ${SLACK_CHANNEL}
  PROJECT_VERSION: ${PROJECT_VERSION}