pipeline:

  build:
    image: maven:latest
    commands:
      - mvn -B -q -s settings.xml package
    when:
      branch: laneweb

  publish:
    image: plugins/docker
    registry: gcr.io
    repo: gcr.io/som-laneweb/laneweb
    tag:
      - latest
      - "${DRONE_COMMIT_SHA}"
    secrets: [ docker_username, docker_password ]
    when:
      status: success
      branch: master

  downstream:
    image: plugins/downstream
    server: https://ci.med.stanford.edu
    repositories:
      - irt-lane/kube-laneweb@master
    fork: true
    secrets: [ downstream_token ]
    when:
      status: success
      branch: master

  slack:
    image: plugins/slack
    channel: irt-dcs-cicd
    username: irt-lane/docker-laneweb
    template: >
      irt-lane/docker-laneweb build #{{ build.number }} finished with a {{ build.status }} status
      Build log: https://ci.med.stanford.edu/irt-lane/docker-laneweb/{{ build.number }}
      Changes: https://gitlab.med.stanford.edu/irt-lane/docker-laneweb/commit/{{ build.commit }}
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      branch: master
