include:
  - project: "irt-lane/som-laneweb"
    file: "/cicd/build-image.yml"
  - project: "irt-lane/som-laneweb"
    file: "/cicd/trigger-downstream.yml"

variables:
  IMAGE_NAME: "laneweb"
  KANIKO_CACHE: "true"

downstream:
  trigger: irt-lane/kube-laneweb

build-image:
  image:
    name: gcr.io/kaniko-project/executor:debug-v1.2.0
  script:
    - /kaniko/executor
        --context $CI_PROJECT_DIR$BUILD_CONTEXT
        --dockerfile $CI_PROJECT_DIR$DOCKER_FILE
        --destination $IMAGE_REPO:latest
        --destination $IMAGE_REPO:stage-latest
        --destination $IMAGE_REPO:$CI_COMMIT_SHA