include:
  - project: "irt-lane/som-laneweb"
    file: "/cicd/build-maven-image.yml"
  - project: "irt-lane/som-laneweb"
    file: "/cicd/sonar-maven-scan.yml"
  - project: "irt-lane/som-laneweb"
    file: "/cicd/snyk-maven-scan.yml"
  - project: "irt-lane/som-laneweb"
    file: "/cicd/trigger-downstream.yml"

variables:
  IMAGE_NAME: "laneweb"
  KANIKO_CACHE: "true"
  SONAR_SCAN_OPT: "-Dspring.profiles.active=gce -Dsonar.qualitygate.wait=true"

downstream:
  trigger: irt-lane/kube-laneweb

