SELECT DISTINCT URL_HOST AS HOST
FROM LMLDB.ELINK_INDEX
WHERE LINK_SUBTYPE         IN ('HTTP','HTTPS')
AND ELINK_INDEX.RECORD_TYPE = 'A'
UNION
SELECT DISTINCT URL_HOST AS HOST
FROM LMLDB.ELINK_INDEX,
  LMLDB.MFHD_MASTER,
  LMLDB.BIB_MFHD,
  LMLDB.BIB_MASTER
WHERE ELINK_INDEX.RECORD_ID    = MFHD_MASTER.MFHD_ID
AND MFHD_MASTER.MFHD_ID = BIB_MFHD.MFHD_ID
AND BIB_MFHD.BIB_ID = BIB_MASTER.BIB_ID
AND LINK_SUBTYPE              IN ('HTTP','HTTPS')
AND ELINK_INDEX.RECORD_TYPE    = 'M'
AND ELINK_INDEX.RECORD_ID NOT IN
  (SELECT MFHD_ID
  FROM LMLDB.MFHD_DATA
  WHERE LOWER(RECORD_SEGMENT) LIKE '%, noproxy%'
  )
AND MFHD_MASTER.SUPPRESS_IN_OPAC != 'Y'
AND BIB_MASTER.SUPPRESS_IN_OPAC != 'Y'
MINUS
SELECT DISTINCT URL_HOST AS HOST
FROM LMLDB.ELINK_INDEX
WHERE LINK_SUBTYPE         IN ('HTTP','HTTPS')
AND ELINK_INDEX.RECORD_TYPE IN ('A', 'M')
AND (URL_HOST LIKE '%.stanford.edu'
OR URL_HOST LIKE 'stanfordhealthcare.org'
OR URL_HOST LIKE 'www.stanfordchildrens.org')